package com.example.brainbrawl.config

object IntentExtras {
    const val UID = "uid"
    const val EMAIL = "email"
    const val NOME_UTILIZADOR = "nomeUtilizador"
    const val NOME_JOGADOR = "nomeJogador"
    const val NOME_AMIGO = "nomeAmigo"
    const val UID_AMIGO = "uidAmigo"
    const val CODIGO_SALA = "codigoSala"
    const val NOME_CATEGORIA = "nomeCategoria"
    const val CATEGORIA_LEGACY = "categoria"
    const val MODO_JOGO = "modoJogo"
    const val ADMIN = "admin"
    const val PONTUACAO = "pontuacao"
    const val TOTAL_PONTOS = "totalPontos"
    const val TOTAL_PERGUNTAS = "totalPerguntas"
    const val NUMERO_PERGUNTAS_CERTAS = "numeroPerguntasCertas"
    const val TOTAL_PERGUNTAS_CERTAS_LEGACY = "totalPerguntascertas"
    const val TOTAL_RESPOSTAS_CERTAS = "totalRespostasCertas"
    const val RESPOSTAS_CERTAS = "respostasCertas"
    const val EQUIPA = "equipa"
    const val PLAYER_KEY = "playerKey"
    const val TIPO_JOGADOR = "tipoJogador"
    const val IS_GUEST = "isGuest"
    const val AVATAR = "avatar"
}
